// Portfolio data — derived from Reda OULD OULHADJ profile
export const PROFILE = {
  name: "Reda OULD OULHADJ",
  role: "Robotics & AI Engineer",
  tagline: "Bridging the gap between classical robotics and AI — perception, navigation, and manipulation under real constraints.",
  location: "Clermont-Ferrand, France",
  email: "redaouldoulhadj@gmail.com",
  phone: "+33 7 45 52 17 25",
  linkedin: "linkedin.com/in/reda-ould-oulhadj",
  status: "M2 Perception Artificielle et Robotique · Université Clermont Auvergne · Graduating 2026",
  stats: [
    { v: "2/42", l: "M1 Rank" },
    { v: "15.97", l: "M1 Avg /20" },
    { v: "C2", l: "French (TCF)" },
    { v: "Fluent", l: "English" },
    { v: "22nd", l: "National Concours" },
    { v: "10+", l: "Robot Comps" },
  ],
};

export const PROJECTS = [
  {
    id: "mobile-manip",
    num: "01",
    year: "2025–26",
    title: "Mobile Manipulation for Technician Assistance",
    tags: ["ROS2", "Isaac Sim", "MoveIt", "Nav2", "RGB-D", "TinyVLA / SmolVLA"],
    blurb: "A mobile robot (FR3 + base) that follows a technician (YOLO-Pose + Kalman), localizes tools via RGB-D, and executes manipulation tasks via VLA models (TinyVLA/SmolVLA) trained on LeRobot/HDF5 data.",
    role: "End-to-end integration · perception · manipulation · data pipeline",
    stack: "ROS2 · Gazebo · Isaac Sim · Nav2 · MoveIt · YOLO-Pose · TinyVLA · SmolVLA · LeRobot",
    highlights: [
      "Human detection & tracking (YOLO-Pose + Kalman)",
      "RGB-D tool localization & pick-place",
      "Closed-loop VLA rollout evaluation",
      "Automated episode collection pipelines",
    ],
    kind: "mobile-manip",
    videos: [
      { src: "assets/videos/m2_smolvla_isaacsim.mp4", label: "SmolVLA in Isaac Sim — autonomous screwdriver pick-and-place from vision" },
      { src: "assets/videos/m2_navigation_gazebo.mp4", label: "Navigation stack — move-to-goal in Gazebo (4×)" },
    ],
    report: { src: "assets/reports/M2_mobile_manipulation.pdf", label: "Project report (PDF)" },
  },
  {
    id: "rl-nav",
    num: "02",
    year: "2025",
    title: "Autonomous Navigation via Reinforcement Learning",
    tags: ["Genesis", "PyTorch", "SAC", "LiDAR"],
    blurb: "End-to-end RL navigation in Genesis Engine. Vectorized simulation with 200+ robots, Soft Actor-Critic (SAC) for obstacle avoidance and goal reaching with GPU acceleration.",
    role: "RL environment design · training pipeline · reward shaping",
    stack: "Genesis Engine · PyTorch · Stable-Baselines3 · SAC · LiDAR · GPU Acceleration",
    highlights: [
      "Training speed > 500 FPS",
      "Vectorized multi-robot simulation",
      "Robust obstacle avoidance in random maps",
    ],
    kind: "rl-nav",
  },
  {
    id: "imitation-manip",
    num: "03",
    year: "2025",
    title: "Imitation Learning for Pick-and-Place",
    tags: ["VLA", "Fine-tuning", "Genesis", "Control"],
    blurb: "Learning-from-demonstration for a manipulator arm. Fine-tuning SmolVLA models on expert data collected in simulation for stable pick-and-place trajectories.",
    role: "Data collection · model fine-tuning · rollout validation",
    stack: "SmolVLA · Genesis · Python · Continuous Control · Demonstration Collection",
    highlights: [
      "Expert demonstration data pipeline",
      "SmolVLA adaptation to manipulation",
      "Generalization to varying object poses",
    ],
    kind: "imitation-manip",
  },
  {
    id: "pointnet",
    num: "04",
    year: "2024",
    title: "PointNet — 3D Point Cloud Classification",
    tags: ["PyTorch", "3D Deep Learning", "ModelNet40"],
    blurb: "PointMLP, vanilla PointNet, and PointNet with input T-Net compared on ModelNet40. Explored permutation invariance, symmetric pooling, augmentations.",
    role: "Training experiments · ablations · analysis",
    stack: "PyTorch · ModelNet40 · T-Net · jitter/shift/scale/dropout augs",
    highlights: [
      "≈ 90% accuracy (tuned)",
      "T-Net: alignment robustness",
      "Shared MLP + symmetric pooling",
      "Careful augmentation study",
    ],
    kind: "pointnet",
    report: { src: "assets/reports/PointNet_3DML.pdf", label: "3D ML report (PDF)" },
  },
  {
    id: "ur3e",
    num: "05",
    year: "2025",
    title: "UR3e Pick-and-Place — ROS2 + MoveIt",
    tags: ["UR3e", "MoveIt", "Polyscope", "Contact Sensing"],
    blurb: "Industrial arm programming: Polyscope pick-and-place, contact sensing, ROS2 + UR driver + MoveIt trajectory planning. Work-frame / TCP understanding in practice.",
    role: "Lab project — manipulator integration",
    stack: "UR3e · Polyscope · ROS2 · UR driver · MoveIt",
    highlights: ["Work-frame / TCP setup", "Contact-aware programs", "MoveIt trajectories on real hardware"],
    kind: "ur3e",
    report: { src: "assets/reports/UR3e_ROS2.pdf", label: "Lab report (PDF)" },
  },
  {
    id: "maze",
    num: "06",
    year: "2023",
    title: "Maze Solver — Webots + Real Robot",
    tags: ["Visual Servoing", "DFS", "OpenCV", "Embedded"],
    blurb: "Unknown-maze explorer. Two-pass: DFS until goal, then direct replay of simplified shortest path. Binary thresholding + image moments + PID steering.",
    role: "Sim-first, then hardware — competition build",
    stack: "Webots · OpenCV thresholding · moments/centroid · PID · turn encoding L/F/R/B",
    highlights: ["DFS exploration", "Path simplification on backtrack", "Visual line following"],
    kind: "maze",
  },
  {
    id: "rc-car",
    num: "07",
    year: "2023",
    title: "RC Race Car — High Performance Build",
    tags: ["Brushless", "SolidWorks", "Teleop", "Mechatronics"],
    blurb: "Custom-built 1:8 scale racing chassis designed for speed (50km/h) and impact resistance. Integrated high-torque brushless power system and custom steering geometry.",
    role: "Chassis design · power electronics · assembly",
    stack: "SolidWorks · Sensored Brushless System · 50kg-cm Servo · 2.4GHz Radio · 3S LiPo",
    highlights: ["Custom Ackermann steering geometry", "Aerodynamic & impact-resistant chassis", "Teleoperation via aircraft-grade RC system"],
    kind: "rc-car",
  },
  {
    id: "bionic-arm",
    num: "08",
    year: "2023",
    title: "Bionic Arm — 3D Printed Prototype",
    tags: ["CAD", "3D Printing", "Bio-mimetic", "SolidWorks"],
    blurb: "A human-scale 5-fingered robotic hand featuring a tendon-driven mechanism and 3D-printed ligaments for biomimetic movement.",
    role: "CAD modeling · assembly · calibration",
    stack: "SolidWorks · 3D Printing (PLA/TPU) · Multi-servo array · Tendon-driven control",
    highlights: ["Underactuated finger mechanism", "Custom tendon routing in CAD", "Lightweight biomimetic structure"],
    kind: "bionic",
  },
  {
    id: "storage-system",
    num: "09",
    year: "2023",
    title: "Autonomous Storage System (Miniature)",
    tags: ["C++", "AS/RS", "Logic", "Industrial"],
    blurb: "A miniature automated storage and retrieval system (AS/RS) implementing grid-based task scheduling and shelf-alignment logic.",
    role: "Firmware development · logic optimization · sensors",
    stack: "C++ · IR Proximity · PID Alignment · Grid-based Scheduler",
    highlights: ["Optimized pathfinding for retrieval", "Reliable shelf-detection calibration", "Automated load/unload sequencing"],
    kind: "industrial",
  },
  {
    id: "limo",
    num: "10",
    year: "2024",
    title: "Robot LIMO — ROS2 Navigation",
    tags: ["ROS2", "LiDAR", "Nav2", "SLAM"],
    blurb: "Navigation stack implementation for the LIMO mobile base. Focused on LiDAR-based mapping, path planning, and joystick-teleop/autonomy bridging.",
    role: "ROS2 development · navigation tuning",
    stack: "ROS2 · Nav2 · LiDAR · Gazebo · LIMO Hardware",
    highlights: ["Map-building via SLAM-toolbox", "Dynamic obstacle avoidance with Nav2", "Sim-to-real deployment"],
    kind: "limo",
  },
  {
    id: "africa-cup",
    num: "11",
    year: "2022–23",
    title: "League of Robotics Africa — Competition",
    tags: ["Raspberry Pi", "OpenCV", "PID", "Teamwork"],
    blurb: "Team of 5. Two robots: (1) teleop miniature mobile manipulator for 1v1, (2) autonomous loading/unloading robot with visual-servoing line following on Pi 4 + HD camera.",
    role: "Robotics maker · embedded · vision",
    stack: "Raspberry Pi 4 · HD Camera · OpenCV · PID steering",
    highlights: ["Two distinct robots shipped", "Line-following via moments", "Competition-grade build"],
    kind: "africa",
  },
  {
    id: "dev-tools",
    num: "12",
    year: "2024–25",
    title: "Software Automation & AI Extensions",
    tags: ["Node.js", "Playwright", "LLM", "Automation"],
    blurb: "A suite of developer tools for browser automation and document management. Includes a Playwright-based AI agent for web tasks and a postulation management engine.",
    role: "Tool building · automation architecture",
    stack: "Node.js · Python · Playwright · Chrome Extensions · LLM Integration",
    highlights: ["Browser batch autofill via AI (agent_browser_ops)", "Automated PDF processing & application engine (m2_postulation)", "Chrome extension for one-shot web tasks"],
    kind: "software",
  },
  {
    id: "teleop-manip",
    num: "13",
    year: "2023",
    title: "Teleoperated Mobile Manipulator",
    tags: ["Arduino", "ROS2", "Simulink", "SolidWorks"],
    blurb: "A custom-built mobile base equipped with a 4-DOF manipulator arm. Features remote control via a dedicated mobile app and integrated simulation-to-reality control logic.",
    role: "System architect · mechatronics integration · app development",
    stack: "Arduino · C · SolidWorks · ROS2 · Simulink · Mobile App (BT/WiFi)",
    highlights: ["4-DOF arm with inverse kinematics", "Mobile app interface for remote control", "Integrated power management for high-load servos"],
    kind: "mobile-manip",
  },
];

export const EXPERIENCE = [
  {
    date: "Mar → Sep 2026",
    title: "Research Internship — RL for Active Exploration",
    org: "Institut Pascal · UCA · Aubière",
    points: [
      "Reinforcement Learning for active contact-based exploration of unseen objects",
      "Vision-Language-Action modeling & multimodal fusion (Tactile, Thermal, Ultrasonic)",
      "Designing continuous observation & action spaces for robotic control",
      "SOTA RL frameworks implementation for language-guided exploration",
    ],
  },
  {
    date: "Apr → Sep 2025",
    title: "Robotics Engineer Intern — Axter Automation",
    org: "Axter Automation · Vaucresson, France",
    points: [
      "Optimized navigation stacks for AGVs (SLAM and Reflector-based)",
      "Integrated advanced sensors: LiDAR R2000, MultiScan, TIM320",
      "C++ / ROS software development for industrial mobile robotics",
      "Field testing and automated charging system improvements",
    ],
  },
  {
    date: "2024",
    title: "Industrial Internship — LD Azouaou Mahindra",
    org: "Agricultural / lifting machinery · Algeria",
    points: [
      "Reverse engineering of industrial elevators using SolidWorks",
      "3D modeling of complex structural and mechanical components",
      "Optimizing design for performance, cost, and energy efficiency",
    ],
  },
  {
    date: "2023",
    title: "Industrial Internship — BETA Makina",
    org: "Industrial Machine Design · Algeria",
    points: [
      "Mechanical design and prototype development",
      "Machining on lathe and milling machines",
      "Manufacturing process optimization",
    ],
  },
  {
    date: "2023",
    title: "Maintenance Internship — SOBCO Palmary",
    org: "Food Industry Production · Algeria",
    points: [
      "Immersion in automated production lines (Chocolate & Biscuits)",
      "Maintenance department operations and troubleshooting",
    ],
  },
];

export const EDUCATION = [
  { date: "2025–26", title: "M2 Perception Artificielle et Robotique", org: "Université Clermont Auvergne", note: "S3: 15.30/20 · Rank 3/16" },
  { date: "2024–25", title: "M1 Automatique Robotique", org: "Université Clermont Auvergne", note: "15.97/20 · Rank 2/42 · Mention Bien" },
  { date: "2020–24", title: "Engineering Cycle — Mechatronics", org: "ENSTA / ENST Algeria", note: "Major of Promotion (2x) · National Concours 22nd/2000+" },
  { date: "2020", title: "Baccalaureat — Math Technique", org: "Lycee Issiakhem", note: "Mention Très Bien · 16.15/20" },
];

export const SKILL_GROUPS = [
  {
    title: "Robotics & Middleware",
    items: ["ROS", "ROS2", "Nav2", "MoveIt", "PX4", "Gazebo", "Isaac Sim", "Genesis", "Webots", "URDF/Xacro"],
  },
  {
    title: "AI & Computer Vision",
    items: ["PyTorch", "OpenCV", "Stable-Baselines3 (RL)", "YOLO", "PointNet", "SmolVLA", "Multimodal Fusion", "3D Vision"],
  },
  {
    title: "Control & Optimization",
    items: ["MPC", "PID", "SAC / PPO (RL)", "Kalman Filters", "Geometric Control", "Path Planning", "IK"],
  },
  {
    title: "Programming & Infrastructure",
    items: ["Python", "C/C++", "Linux (Ubuntu)", "Git", "Docker", "HDF5", "Playwright"],
  },
  {
    title: "CAD & Fabrication",
    items: ["SolidWorks", "Catia", "AutoCAD", "PCB Design", "3D Printing", "Machining"],
  },
  {
    title: "Languages",
    items: ["French (C2)", "English (Fluent)", "Arabic (Bilingual)", "Kabyle (Native)"],
  },
];
